language: tools
sudo: required

install: mvn cobertura:cobertura && cd tools && mvn clean install && cd ../spawn && mvn clean install

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  fast_finish: true

  include:
    - jdk: oraclejdk8
      addons:
        apt:
          packages:
            - oracle-java8-installer
    - jdk: oraclejdk9
      addons:
        apt:
          packages:
            - oracle-java9-installer

notifications:
  email: false
  