language: java
dist: trusty
sudo: required

os:
- linux
- osx

jdk:
- openjdk9
- openjdk10

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: openjdk8
  allow_failures:
  - jdk: openjdk11
  - jdk: openjdk-ea
  - jdk: oraclejdk-ea

before_install:
- unset _JAVA_OPTIONS

before_scipt:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}

script:
- java -version 
