language: java
language: java
dist: trusty
sudo: required

install: script/install.sh

matrix:
  fast_finish: false

  include:
    - env: JDK='Oracle JDK 8'
      jdk: oraclejdk8
    - env: JDK='Oracle JDK 9'
      jdk: oraclejdk9
    - env: JDK='Oracle JDK 10'
      install: script/build-script.sh F 10
    - env: JDK='Oracle JDK 11'
      install: script/build-script.sh F 11 -L BCL
  allow_failures:
    - env: JDK='Oracle JDK 9'
    - env: JDK='Oracle JDK 11'

script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version

notifications:
  email: false 
