language: java
dist: trusty
sudo: false

os:
- linux
- osx

jdk:
- openjdk9
- openjdk10
- openjdk11
- openjdk-ea
- oraclejdk-ea

matrix:
  fast_finish: true
  include:
  - os: linux
    jdk: openjdk8
  - os: osx
    jdk: openjdk8

before_install:
- unset _JAVA_OPTIONS

before_scipt:
- echo JAVA_HOME = ${JAVA_HOME}
- echo PATH = ${PATH}

script:
- java -version 
